### port to serve the metrics:
port: 16061
### collector interval in seconds:
interval: 60
### logging verbosity: 0=warning, 1=success, 2=info, 3=debug, 4=trace
verbosity: 4

fsa_metrics:
- scan_dir: "/var/backups/"
  pattern: "**"
- scan_dir: "/var/spool/"
  pattern: "**"
